[project]
name = "nanochat"
version = "0.1.0"
description = "the minimal full-stack ChatGPT clone"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets==4.0.0",
    "fastapi>=0.117.1",
    "kernels==0.11.7",
    "psutil==7.1.0",
    "rustbpe>=0.1.0",
    "tokenizers>=0.22.0",
    "uvicorn>=0.36.0",
    "wandb>=0.21.3",
    "PyYAML==6.0.3",
    "huggingface_hub==1.14.0",
    "pillow==10.4.0",
    "pyarrow==21.0.0",
    "requests==2.33.1",
    "sentence-transformers==5.4.1",
    "tiktoken==0.11.0",
    "transformers==5.6.2",
    "numpy==1.26.4",
    "tensorboard-plugin-profile==2.22.1",
    "pycocotools==2.0.11",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "pytest>=8.0.0",
    "python-dotenv>=1.2.1",
    "transformers>=4.57.3",
]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

# target torch to cuda 12.4 or CPU
[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cu124", extra = "gpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[project.optional-dependencies]
cpu = [
    "torch==2.6.0+cpu", # Explicitly require the CPU wheel here
]
gpu = [
    "torch==2.6.0+cu124",
]

[tool.uv]
default-groups = []
conflicts = [
    [
        { extra = "cpu" },
        { extra = "gpu" },
    ],
]
